#!/usr/bin/env python3
"""Generate a dimensional SPARTA lid-driven-cavity input deck."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import shutil


K_B = 1.380649e-23
ARGON_MASS = 6.63e-26
DIAMETER_REF = 4.17e-10
TEMPERATURE_REF = 273.0
VISCOSITY_INDEX = 0.81
VHS_ALPHA = 1.0
WALL_TEMPERATURE = 300.0
LID_VELOCITY = 100.0

PRESETS = {
    "smoke": {"nx": 12, "ppc": 4, "warmup": 20, "sample": 30, "stride": 2},
    "tutorial": {"nx": 50, "ppc": 12, "warmup": 4000, "sample": 8000, "stride": 5},
    "production": {"nx": 200, "ppc": 32, "warmup": 14000, "sample": 26000, "stride": 10},
}


def physical_parameters(
    kn: float, length: float, nx: int, ppc: int, temperature: float
) -> dict[str, float | int]:
    """Return dimensional case parameters from Kn, L, and the grid preset."""
    mean_free_path = kn * length
    number_density = 1.0 / (
        math.sqrt(2.0) * math.pi * DIAMETER_REF**2 * mean_free_path
    )
    nparticles = nx * nx * ppc
    # In a SPARTA 2-D calculation, fnum is a molecule count per unit depth.
    fnum = number_density * length**2 / nparticles
    most_probable_speed = math.sqrt(2.0 * K_B * temperature / ARGON_MASS)
    dx = length / nx
    dt = 0.25 * dx / (4.0 * most_probable_speed + LID_VELOCITY)
    collision_time = mean_free_path / most_probable_speed
    return {
        "mean_free_path": mean_free_path,
        "number_density": number_density,
        "nparticles": nparticles,
        "fnum": fnum,
        "dx": dx,
        "dx_over_lambda": dx / mean_free_path,
        "dt": dt,
        "mean_collision_time": collision_time,
        "dt_over_collision_time": dt / collision_time,
    }


def write_input(
    output: Path, level: str, kn: float, length: float, seed: int
) -> dict[str, object]:
    preset = PRESETS[level]
    nx = int(preset["nx"])
    ppc = int(preset["ppc"])
    warmup = int(preset["warmup"])
    sample = int(preset["sample"])
    stride = int(preset["stride"])
    values = physical_parameters(kn, length, nx, ppc, WALL_TEMPERATURE)

    output.mkdir(parents=True, exist_ok=True)
    root = Path(__file__).resolve().parents[1]
    for name in ("argon.species", "argon.vss"):
        shutil.copy2(root / "data" / name, output / name)

    deck = f"""# Generated by scripts/generate_case.py.
# Two-dimensional rarefied lid-driven cavity; VHS argon; fully diffuse walls.

units                si
seed                 {seed}
dimension            2
boundary             s s p

create_box           0.0 {length:.16e} 0.0 {length:.16e} -0.5 0.5
create_grid          {nx} {nx} 1

global               nrho {values['number_density']:.16e} fnum {values['fnum']:.16e} temp {WALL_TEMPERATURE:.8g}
species              argon.species Ar
mixture              gas Ar nrho {values['number_density']:.16e} temp {WALL_TEMPERATURE:.8g} vstream 0.0 0.0 0.0

surf_collide         fixed diffuse {WALL_TEMPERATURE:.8g} 1.0
surf_collide         lid diffuse {WALL_TEMPERATURE:.8g} 1.0 translate {LID_VELOCITY:.8g} 0.0 0.0
bound_modify         xlo xhi ylo collide fixed
bound_modify         yhi collide lid

# SPARTA calls the style vss; alpha=1.0 in argon.vss selects the VHS limit.
collide              vss gas argon.vss
create_particles     gas n 0
timestep             {values['dt']:.16e}

stats                {max(10, min(1000, warmup // 10 if warmup else 10))}
stats_style          step cpu np nattempt ncoll nscoll
run                  {warmup}

reset_timestep       0
compute              flow grid all gas nrho u v w temp
fix                  flowavg ave/grid all {stride} 1 {stride} c_flow[*] ave running
dump                 fields grid all {sample} grid.final.* id xc yc f_flowavg[*]
dump_modify          fields pad 8
run                  {sample}
"""
    (output / "in.cavity").write_text(deck, encoding="utf-8")

    metadata: dict[str, object] = {
        "case": "two-dimensional rarefied lid-driven cavity",
        "purpose": "SPARTA teaching example",
        "level": level,
        "kn": kn,
        "length_m": length,
        "nx": nx,
        "ny": nx,
        "particles_per_cell": ppc,
        "wall_temperature_K": WALL_TEMPERATURE,
        "lid_velocity_m_per_s": LID_VELOCITY,
        "argon_mass_kg": ARGON_MASS,
        "diameter_ref_m": DIAMETER_REF,
        "temperature_ref_K": TEMPERATURE_REF,
        "viscosity_index": VISCOSITY_INDEX,
        "vhs_alpha": VHS_ALPHA,
        "warmup_steps": warmup,
        "sample_steps": sample,
        "sample_stride": stride,
        "seed": seed,
        **values,
    }
    (output / "case_metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--level", choices=PRESETS, default="tutorial")
    parser.add_argument("--kn", type=float, default=0.1)
    parser.add_argument("--length", type=float, default=1.0e-6)
    parser.add_argument("--seed", type=int, default=20260803)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.kn <= 0.0 or args.length <= 0.0:
        parser.error("--kn and --length must be positive")
    metadata = write_input(
        args.output.resolve(), args.level, args.kn, args.length, args.seed
    )
    print(json.dumps(metadata, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

