#!/usr/bin/env python3
"""Generate the SPARTA cavity case at the Gu viscosity-based Kn_Gu=0.20."""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import generate_jfm_kn020_case as base


GU_TO_VHS_MFP = (
    15.0
    * math.pi
    / (2.0 * (5.0 - 2.0 * base.VISCOSITY_INDEX) * (7.0 - 2.0 * base.VISCOSITY_INDEX))
)


def write_case(
    output: Path,
    *,
    seed: int,
    kn_gu: float = 0.20,
    length: float = 1.0e-6,
    nx: int = 160,
    ppc: int = 256,
    warmup_steps: int = 40_000,
    sample_steps: int = 200_000,
    sample_stride: int = 10,
    checkpoint_steps: int = 40_000,
) -> dict[str, object]:
    """Use the existing validated deck writer with the equivalent VHS Kn."""

    kn_vhs = kn_gu / GU_TO_VHS_MFP
    metadata = base.write_case(
        output,
        seed=seed,
        kn=kn_vhs,
        length=length,
        nx=nx,
        ppc=ppc,
        warmup_steps=warmup_steps,
        sample_steps=sample_steps,
        sample_stride=sample_stride,
        checkpoint_steps=checkpoint_steps,
    )

    lambda_vhs = float(metadata.pop("mean_free_path_m"))
    dx_over_lambda_vhs = float(metadata.pop("dx_over_lambda"))
    collision_time_vhs = float(metadata.pop("mean_collision_time_s"))
    dt_over_collision_time_vhs = float(metadata.pop("dt_over_collision_time"))

    metadata.update(
        {
            "case": "JFM matched Gu-Knudsen lid-driven cavity",
            "kn": kn_gu,
            "kn_gu": kn_gu,
            "kn_vhs_collision_diameter": kn_vhs,
            "kn_convention": "gu_lambda_over_L",
            "kn_definition": (
                "lambda_Gu/L with lambda_Gu=15/[2*sqrt(2)*(5-2*omega)*"
                "(7-2*omega)*d_ref^2*n]*(T/T_ref)^(omega-1/2)"
            ),
            "gu_to_vhs_mean_free_path_factor": GU_TO_VHS_MFP,
            "mean_free_path_gu_m": kn_gu * length,
            "mean_free_path_vhs_m": lambda_vhs,
            "dx_over_lambda_gu": (length / nx) / (kn_gu * length),
            "dx_over_lambda_vhs": dx_over_lambda_vhs,
            "mean_collision_time_vhs_s": collision_time_vhs,
            "dt_over_collision_time_vhs": dt_over_collision_time_vhs,
            "evidence_level": "two_seed_publication_ensemble",
        }
    )

    expected_density = 15.0 / (
        2.0
        * math.sqrt(2.0)
        * (5.0 - 2.0 * base.VISCOSITY_INDEX)
        * (7.0 - 2.0 * base.VISCOSITY_INDEX)
        * base.DIAMETER_REF**2
        * kn_gu
        * length
    ) * (base.WALL_TEMPERATURE / base.TEMPERATURE_REF) ** (
        base.VISCOSITY_INDEX - 0.5
    )
    # SPARTA 2-D uses unit depth; the base generator therefore represents
    # n*L^2 molecules with nx*nx*ppc simulator particles.
    expected_fnum = expected_density * length**2 / (nx * nx * ppc)
    if not math.isclose(
        float(metadata["number_density_m-3"]), expected_density, rel_tol=2.0e-15
    ):
        raise RuntimeError("corrected Gu-Kn number density check failed")
    if not math.isclose(float(metadata["fnum"]), expected_fnum, rel_tol=2.0e-15):
        raise RuntimeError("corrected Gu-Kn fnum check failed")

    metadata_path = output / "case_metadata.json"
    metadata_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    deck_path = output / "in.cavity"
    deck_lines = deck_path.read_text(encoding="utf-8").splitlines()
    deck_lines[0] = "# Generated by generate_jfm_kngu020_case.py; do not hand-edit."
    deck_lines[1] = (
        f"# Matched case: Kn_Gu={kn_gu:.16g}; "
        f"equivalent Kn_VHS={kn_vhs:.16g} at omega={base.VISCOSITY_INDEX:.8g}."
    )
    deck_path.write_text("\n".join(deck_lines) + "\n", encoding="utf-8")
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--kn-gu", type=float, default=0.20)
    parser.add_argument("--length", type=float, default=1.0e-6)
    parser.add_argument("--nx", type=int, default=160)
    parser.add_argument("--ppc", type=int, default=256)
    parser.add_argument("--warmup", type=int, default=40_000)
    parser.add_argument("--sample", type=int, default=200_000)
    parser.add_argument("--stride", type=int, default=10)
    parser.add_argument("--checkpoint", type=int, default=40_000)
    args = parser.parse_args()
    metadata = write_case(
        args.output.resolve(),
        seed=args.seed,
        kn_gu=args.kn_gu,
        length=args.length,
        nx=args.nx,
        ppc=args.ppc,
        warmup_steps=args.warmup,
        sample_steps=args.sample,
        sample_stride=args.stride,
        checkpoint_steps=args.checkpoint,
    )
    print(json.dumps(metadata, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
