#!/usr/bin/env python3
"""Generate the matched JFM Kn=0.20 SPARTA lid-driven-cavity case."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


K_B = 1.380649e-23
MASS = 6.6335e-26
DIAMETER_REF = 4.17e-10
TEMPERATURE_REF = 273.0
VISCOSITY_INDEX = 0.81
VSS_ALPHA = 1.0
WALL_TEMPERATURE = 300.0
LID_VELOCITY = 100.0


def physical_parameters(
    kn: float,
    length: float,
    nx: int,
    ppc: int,
    temperature: float,
) -> dict[str, float | int]:
    """Return dimensional DSMC parameters for the manuscript's VHS Kn convention."""
    mean_free_path = kn * length
    temperature_factor = (TEMPERATURE_REF / temperature) ** (
        VISCOSITY_INDEX - 0.5
    )
    number_density = 1.0 / (
        math.sqrt(2.0)
        * math.pi
        * DIAMETER_REF**2
        * mean_free_path
        * temperature_factor
    )
    nparticles = nx * nx * ppc
    # SPARTA 2-D uses unit depth, so the represented molecule count is n*L^2.
    fnum = number_density * length**2 / nparticles
    most_probable_speed = math.sqrt(2.0 * K_B * temperature / MASS)
    dx = length / nx
    dt = 0.25 * dx / (4.0 * most_probable_speed + LID_VELOCITY)
    collision_time = mean_free_path / most_probable_speed
    return {
        "mean_free_path_m": mean_free_path,
        "vhs_temperature_factor": temperature_factor,
        "number_density_m-3": number_density,
        "initial_simulator_particles": nparticles,
        "fnum": fnum,
        "dx_m": dx,
        "dx_over_lambda": dx / mean_free_path,
        "dt_s": dt,
        "mean_collision_time_s": collision_time,
        "dt_over_collision_time": dt / collision_time,
    }


def write_case(
    output: Path,
    *,
    seed: int,
    kn: float = 0.20,
    length: float = 1.0e-6,
    nx: int = 160,
    ppc: int = 256,
    warmup_steps: int = 40_000,
    sample_steps: int = 200_000,
    sample_stride: int = 10,
    checkpoint_steps: int = 40_000,
) -> dict[str, object]:
    if min(kn, length, nx, ppc, sample_steps, sample_stride) <= 0:
        raise ValueError("Kn, length, grid, PPC, sample steps, and stride must be positive")
    if warmup_steps < 0 or checkpoint_steps < 0:
        raise ValueError("warmup and checkpoint steps cannot be negative")
    if sample_steps % sample_stride:
        raise ValueError("sample_steps must be divisible by sample_stride")
    if checkpoint_steps and checkpoint_steps % sample_stride:
        raise ValueError("checkpoint_steps must be divisible by sample_stride")

    output.mkdir(parents=True, exist_ok=False)
    values = physical_parameters(kn, length, nx, ppc, WALL_TEMPERATURE)
    samples_per_cell = sample_steps // sample_stride

    (output / "argon.species").write_text(
        "# ID molwt(amu) mass(kg) rotdof rotrel vibdof vibrel vibtemp(K) weight charge\n"
        f"Ar 40.00 {MASS:.10e} 0 0.0 0 0.0 0.0 1.0 0.0\n",
        encoding="utf-8",
    )
    (output / "argon.vss").write_text(
        "# ID diameter(m) omega Tref(K) alpha\n"
        f"Ar {DIAMETER_REF:.10e} {VISCOSITY_INDEX:.8g} "
        f"{TEMPERATURE_REF:.8g} {VSS_ALPHA:.8g}\n",
        encoding="utf-8",
    )

    checkpoint_block = ""
    if checkpoint_steps:
        checkpoint_block = f"""dump                 checkpoints grid all {checkpoint_steps} grid.checkpoint.* id xc yc f_fieldavg[*]
dump_modify          checkpoints pad 8
restart              {checkpoint_steps} restart.kn020.1 restart.kn020.2
"""

    deck = f"""# Generated by generate_jfm_kn020_case.py; do not hand-edit.
# Matched high-Kn reviewer case: Kn=lambda_0/L=0.20 at T_w=300 K.

units                si
seed                 {seed}
dimension            2
boundary             s s p

create_box           0.0 {length:.16e} 0.0 {length:.16e} -0.5 0.5
create_grid          {nx} {nx} 1

global               nrho {values['number_density_m-3']:.16e} fnum {values['fnum']:.16e} temp {WALL_TEMPERATURE:.8g}
species              argon.species Ar
mixture              gas Ar nrho {values['number_density_m-3']:.16e} temp {WALL_TEMPERATURE:.8g} vstream 0.0 0.0 0.0

surf_collide         fixed diffuse {WALL_TEMPERATURE:.8g} 1.0
surf_collide         lid diffuse {WALL_TEMPERATURE:.8g} 1.0 translate {LID_VELOCITY:.8g} 0.0 0.0
bound_modify         xlo xhi ylo collide fixed
bound_modify         yhi collide lid

collide              vss gas argon.vss
create_particles     gas n 0
timestep             {values['dt_s']:.16e}

stats                1000
stats_style          step cpu np nattempt ncoll nscoll
run                  {warmup_steps}

reset_timestep       0
# COM-subtracted translational temperature and heat-flux density are required
# for the R13/R26/DSMC anti-Fourier comparison.
compute              flow grid all gas nrho u v w
compute              thermal thermal/grid all gas temp
compute              heat eflux/grid all gas heatx heaty
fix                  fieldavg ave/grid all {sample_stride} 1 {sample_stride} c_flow[*] c_thermal[*] c_heat[*] ave running
{checkpoint_block}dump                 final grid all {sample_steps} grid.final.* id xc yc f_fieldavg[*]
dump_modify          final pad 8
run                  {sample_steps}
"""
    (output / "in.cavity").write_text(deck, encoding="utf-8")

    metadata: dict[str, object] = {
        "case": "JFM matched high-Kn lid-driven cavity",
        "kn": kn,
        "kn_convention": "gu_lambda_over_L",
        "kn_definition": (
            "lambda_0/L; equilibrium VHS mean free path at wall temperature: "
            "lambda_0=[sqrt(2)*pi*d_ref^2*n*(T_ref/T_w)^(omega-1/2)]^-1"
        ),
        "length_m": length,
        "nx": nx,
        "ny": nx,
        "particles_per_cell": ppc,
        "wall_temperature_K": WALL_TEMPERATURE,
        "lid_velocity_m_per_s": LID_VELOCITY,
        "argon_mass_kg": MASS,
        "diameter_ref_m": DIAMETER_REF,
        "temperature_ref_K": TEMPERATURE_REF,
        "viscosity_index": VISCOSITY_INDEX,
        "vss_alpha": VSS_ALPHA,
        "warmup_steps": warmup_steps,
        "sample_steps": sample_steps,
        "sample_stride": sample_stride,
        "accumulated_samples_per_cell": samples_per_cell,
        "checkpoint_frequency_steps": checkpoint_steps,
        "seed": seed,
        "temperature_observable": "thermal/grid COM-subtracted translational temperature",
        "heat_flux_observable": "eflux/grid COM-subtracted heat-flux density",
        "dump_columns": ["nrho", "u", "v", "w", "T", "qx", "qy"],
        "evidence_level": "publication-ensemble-pending",
        **values,
    }
    (output / "case_metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--kn", type=float, default=0.20)
    parser.add_argument("--length", type=float, default=1.0e-6)
    parser.add_argument("--nx", type=int, default=160)
    parser.add_argument("--ppc", type=int, default=256)
    parser.add_argument("--warmup", type=int, default=40_000)
    parser.add_argument("--sample", type=int, default=200_000)
    parser.add_argument("--stride", type=int, default=10)
    parser.add_argument("--checkpoint", type=int, default=40_000)
    args = parser.parse_args()
    metadata = write_case(
        args.output.resolve(),
        seed=args.seed,
        kn=args.kn,
        length=args.length,
        nx=args.nx,
        ppc=args.ppc,
        warmup_steps=args.warmup,
        sample_steps=args.sample,
        sample_stride=args.stride,
        checkpoint_steps=args.checkpoint,
    )
    print(json.dumps(metadata, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
