#!/usr/bin/env python3
"""Generate a dimensional SPARTA lid-driven-cavity input deck."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import shutil


K_B = 1.380649e-23
MASS = 6.63e-26
DIAMETER_REF = 4.17e-10
TEMPERATURE_REF = 273.0
VISCOSITY_INDEX = 0.81

PRESETS = {
    "smoke": {"nx": 12, "ppc": 4, "warmup": 20, "sample": 30, "sample_stride": 2},
    "student": {"nx": 50, "ppc": 12, "warmup": 4000, "sample": 8000, "sample_stride": 5},
    "production": {"nx": 200, "ppc": 32, "warmup": 14000, "sample": 26000, "sample_stride": 10},
    "hq": {"nx": 200, "ppc": 128, "warmup": 40000, "sample": 160000, "sample_stride": 10},
    "ultra": {
        "nx": 200,
        "ppc": 128,
        "warmup": 40000,
        "sample": 640000,
        "sample_stride": 10,
        "dump_frequency": 80000,
        "restart_frequency": 80000,
    },
}


def physical_parameters(kn: float, length: float, nx: int, ppc: int, temperature: float) -> dict[str, float]:
    mean_free_path = kn * length
    number_density = 1.0 / (
        math.sqrt(2.0) * math.pi * DIAMETER_REF**2 * mean_free_path
    )
    nparticles = nx * nx * ppc
    # SPARTA 2-D uses unit depth, so the represented molecule count is n*L^2.
    fnum = number_density * length**2 / nparticles
    most_probable_speed = math.sqrt(2.0 * K_B * temperature / MASS)
    dx = length / nx
    dt = 0.25 * dx / (4.0 * most_probable_speed + 100.0)
    collision_time = mean_free_path / most_probable_speed
    return {
        "mean_free_path": mean_free_path,
        "number_density": number_density,
        "nparticles": nparticles,
        "fnum": fnum,
        "dx": dx,
        "dx_over_lambda": dx / mean_free_path,
        "dt": dt,
        "mean_collision_time": collision_time,
        "dt_over_collision_time": dt / collision_time,
    }


def write_input(output: Path, level: str, kn: float, length: float, seed: int) -> dict[str, object]:
    preset = PRESETS[level]
    nx = int(preset["nx"])
    ppc = int(preset["ppc"])
    warmup = int(preset["warmup"])
    sample = int(preset["sample"])
    sample_stride = int(preset["sample_stride"])
    dump_frequency = int(preset.get("dump_frequency", sample))
    restart_frequency = int(preset.get("restart_frequency", 0))
    wall_temperature = 300.0
    lid_velocity = 100.0
    values = physical_parameters(kn, length, nx, ppc, wall_temperature)

    output.mkdir(parents=True, exist_ok=True)
    root = Path(__file__).resolve().parents[1]
    for name in ("argon.species", "argon.vss"):
        shutil.copy2(root / "data" / name, output / name)

    restart_line = (
        f"restart              {restart_frequency} restart.ultra.1 restart.ultra.2\n"
        if restart_frequency else ""
    )
    deck = f"""# Generated by scripts/generate_case.py -- do not hand-edit generated values.
# Mohammadzadeh et al., Physical Review E 85, 056310 (2012)

units                si
seed                 {seed}
dimension            2
boundary             s s p

create_box           0.0 {length:.16e} 0.0 {length:.16e} -0.5 0.5
create_grid          {nx} {nx} 1

global               nrho {values['number_density']:.16e} fnum {values['fnum']:.16e} temp {wall_temperature:.8g}
species              argon.species Ar
mixture              gas Ar nrho {values['number_density']:.16e} temp {wall_temperature:.8g} vstream 0.0 0.0 0.0

surf_collide         fixed diffuse {wall_temperature:.8g} 1.0
surf_collide         lid diffuse {wall_temperature:.8g} 1.0 translate {lid_velocity:.8g} 0.0 0.0
bound_modify         xlo xhi ylo collide fixed
bound_modify         yhi collide lid

collide              vss gas argon.vss
create_particles     gas n 0
timestep             {values['dt']:.16e}

stats                {max(10, min(1000, warmup // 10 if warmup else 10))}
stats_style          step cpu np nattempt ncoll nscoll
run                  {warmup}

reset_timestep       0
compute              flow grid all gas nrho u v w temp
fix                  flowavg ave/grid all {sample_stride} 1 {sample_stride} c_flow[*] ave running
dump                 fields grid all {dump_frequency} grid.final.* id xc yc f_flowavg[*]
dump_modify          fields pad 8
{restart_line}run                  {sample}
"""
    (output / "in.cavity").write_text(deck, encoding="utf-8")

    metadata: dict[str, object] = {
        "level": level,
        "benchmark": "Mohammadzadeh et al., PRE 85, 056310 (2012)",
        "kn": kn,
        "length_m": length,
        "nx": nx,
        "ny": nx,
        "particles_per_cell": ppc,
        "wall_temperature_K": wall_temperature,
        "lid_velocity_m_per_s": lid_velocity,
        "argon_mass_kg": MASS,
        "diameter_ref_m": DIAMETER_REF,
        "temperature_ref_K": TEMPERATURE_REF,
        "viscosity_index": VISCOSITY_INDEX,
        "vhs_alpha": 1.0,
        "warmup_steps": warmup,
        "sample_steps": sample,
        "sample_stride": sample_stride,
        "dump_frequency_steps": dump_frequency,
        "restart_frequency_steps": restart_frequency,
        "seed": seed,
        **values,
        "evidence_level": {
            "smoke": "syntax-smoke",
            "student": "classroom-learning",
            "production": "production-validation-pending",
            "hq": "high-statistics-validation-pending",
            "ultra": "ultra-statistics-validation-pending",
        }[level],
    }
    (output / "case_metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--level", choices=PRESETS, default="student")
    parser.add_argument("--kn", type=float, default=0.1)
    parser.add_argument("--length", type=float, default=1.0e-6)
    parser.add_argument("--seed", type=int, default=20260803)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.kn <= 0.0 or args.length <= 0.0:
        parser.error("--kn and --length must be positive")
    metadata = write_input(args.output.resolve(), args.level, args.kn, args.length, args.seed)
    print(json.dumps(metadata, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
