#!/usr/bin/env python3
"""Provide the manuscript-wide journal figure system and redraw Figures 1--2.

Figures 1 and 2 are native vector graphics. Figures 3--8 are regenerated by
``cavity_journal_figures.py``, Figures 9--17 by
``cylinder_journal_figures.py``, and Figures 18--20 by
``mach12_manuscript_figures.py``. Dense sampled fields are rasterised at
publication resolution and wrapped in robust PDF containers rather than
expanded into millions of vector polygons.

Every output is intended for a dedicated landscape manuscript page.  The
visual system follows a colour-blind-safe palette, 13--15 pt final text, thick
data strokes, unobtrusive grids, and legends outside data regions.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Arc, Circle, FancyArrowPatch, FancyBboxPatch, Rectangle, Wedge
import numpy as np
from PIL import Image, ImageChops, ImageOps
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


NAVY = "#17365D"
BLUE = "#3B6FB6"
TEAL = "#008A93"
GREEN = "#2E8B57"
ORANGE = "#D8742F"
RED = "#C44E52"
PURPLE = "#7A5195"
GRAY = "#5B6573"
LIGHT = "#F4F6F8"


LEGACY = (
    "cavity_ensemble_physical_diagnostics",
    "cavity_kn0p08_u350_qy_fields_and_errors",
    "cavity_kn0p1_u400_qy_fields_and_errors",
    "cavity_qy_vertical_profiles",
    "cavity_qy_horizontal_profiles",
    "cavity_spectral_and_cancellation",
    "cylinder_native_representation",
    "cylinder_fresh_pair01_qy_fields_and_errors",
    "cylinder_ensemble_physical_diagnostics",
    "cylinder_near_wall_normal_heat_flux_profiles",
    "cylinder_near_wall_normal_heat_flux_errors",
    "cylinder_prior_correction_fields",
    "cylinder_wake_qy_profiles",
    "cylinder_fresh_pair01_heat_flux_magnitude",
    "cylinder_polar_qn_structure",
)


def set_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "mathtext.fontset": "stixsans",
            "font.size": 21,
            "axes.labelsize": 24,
            "xtick.labelsize": 19,
            "ytick.labelsize": 19,
            "legend.fontsize": 19,
            "axes.linewidth": 1.8,
            "lines.linewidth": 3.4,
            "lines.markersize": 9.0,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "savefig.facecolor": "white",
        }
    )


def panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(
        0.012,
        0.985,
        label,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=24,
        fontweight="bold",
        color=NAVY,
    )


def save_vector(fig: plt.Figure, out: Path, stem: str) -> None:
    for suffix in ("pdf", "svg"):
        fig.savefig(out / f"{stem}.{suffix}", bbox_inches="tight", pad_inches=0.04)
    fig.savefig(out / f"{stem}.png", dpi=300, bbox_inches="tight", pad_inches=0.04)
    plt.close(fig)


def rounded_box(ax: plt.Axes, xy: tuple[float, float], wh: tuple[float, float], text: str, face: str) -> FancyBboxPatch:
    x, y = xy
    w, h = wh
    box = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.018,rounding_size=0.035",
        linewidth=1.4,
        edgecolor=NAVY,
        facecolor=face,
    )
    ax.add_patch(box)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=18, color="#17202A", linespacing=1.16)
    return box


def arrow(ax: plt.Axes, start: tuple[float, float], end: tuple[float, float], color: str = GRAY, style: str = "-") -> None:
    ax.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle="-|>",
            mutation_scale=14,
            linewidth=1.6,
            linestyle=style,
            color=color,
            shrinkA=2,
            shrinkB=2,
            connectionstyle="arc3,rad=0.0",
        )
    )


def workflow_figure(out: Path) -> None:
    fig, ax = plt.subplots(figsize=(19.0, 6.8), constrained_layout=True)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    rounded_box(ax, (0.025, 0.55), (0.14, 0.22), "Locked additive\nDSMC moment blocks", "#DDEAF6")
    rounded_box(ax, (0.205, 0.62), (0.145, 0.18), "Current observation\n$B=3$ disjoint blocks", "#FFF0D2")
    rounded_box(ax, (0.205, 0.25), (0.145, 0.18), "Independent comparator\nRaw-$B=10$", "#E3F1E5")
    rounded_box(ax, (0.39, 0.62), (0.15, 0.18), "Frozen geometry-native\nstructured prior", "#DDF3F1")
    rounded_box(ax, (0.58, 0.62), (0.17, 0.18), "Observation-conditioned\ndata-consistent correction", "#EEE4F3")
    rounded_box(
        ax,
        (0.58, 0.25),
        (0.17, 0.21),
        "Reconstructed moment vector\n" + r"$\mathbf{y}=(n,u,v,T,P_{xx},P_{xy},P_{yy},q_x,q_y)$",
        "#F8E2E2",
    )
    rounded_box(ax, (0.80, 0.42), (0.17, 0.22), "Locked paired evaluation\nfield NRMSE and $q_n$", "#E7EBF0")

    arrow(ax, (0.165, 0.67), (0.205, 0.71))
    arrow(ax, (0.165, 0.62), (0.205, 0.34))
    arrow(ax, (0.35, 0.71), (0.39, 0.71))
    arrow(ax, (0.54, 0.71), (0.58, 0.71))
    arrow(ax, (0.665, 0.62), (0.665, 0.46))
    arrow(ax, (0.75, 0.69), (0.80, 0.57))
    arrow(ax, (0.75, 0.35), (0.80, 0.48))
    arrow(ax, (0.35, 0.34), (0.80, 0.45), color=GREEN, style="--")

    ax.text(0.43, 0.91, "Prediction path", ha="center", va="center", fontsize=21, color=NAVY, fontweight="bold")
    ax.text(0.48, 0.16, "The independent trajectory is inaccessible until the prediction is locked", ha="center", fontsize=19, color=GREEN)
    ax.plot([0.205, 0.965], [0.20, 0.20], color=GREEN, linewidth=1.6)
    ax.text(0.69, 0.85, "No reference fitting; no neural retraining", ha="center", color=RED, fontsize=19, fontweight="bold")
    ax.text(
        0.50,
        0.055,
        "Cavity development  →  frozen transfer  →  cylinder-native representation  →  prospective confirmation  →  Mach-12 condition-shift audit",
        ha="center",
        va="center",
        fontsize=18,
        color="#202A34",
        bbox={"boxstyle": "round,pad=0.35", "facecolor": LIGHT, "edgecolor": "#B8C2CC"},
    )
    panel_label(ax, "")
    save_vector(fig, out, "workflow_sampling_protocol")


def geometry_figure(out: Path) -> None:
    fig = plt.figure(figsize=(19.0, 7.6))
    grid = fig.add_gridspec(1, 2, width_ratios=[1.00, 1.35], left=0.055, right=0.985, bottom=0.10, top=0.90, wspace=0.20)
    ax = fig.add_subplot(grid[0, 0])
    ax2 = fig.add_subplot(grid[0, 1])

    # Square cavity.
    ax.add_patch(Rectangle((0, 0), 1, 1, facecolor="#F4F8FB", edgecolor=NAVY, linewidth=2.0))
    for x in np.linspace(0, 1, 11):
        ax.plot([x, x], [0, 1], color="#D6DEE6", linewidth=0.65, zorder=0)
        ax.plot([0, 1], [x, x], color="#D6DEE6", linewidth=0.65, zorder=0)
    ax.add_patch(FancyArrowPatch((0.16, 1.09), (0.82, 1.09), arrowstyle="-|>", mutation_scale=18, linewidth=2.4, color=RED))
    ax.text(0.49, 1.17, r"Moving lid: $U_{\rm lid}$", ha="center", color=RED, fontsize=21)
    ax.text(0.50, 0.61, "Cavity domain", ha="center", fontsize=23, fontweight="bold", color=NAVY)
    ax.text(0.50, 0.47, r"$Kn=0.08$ and $0.10$", ha="center", fontsize=21, color=TEAL)
    # Sampling blocks.
    for i in range(3):
        ax.add_patch(Rectangle((0.09 + 0.055 * i, -0.20), 0.04, 0.065, facecolor=ORANGE, edgecolor="none"))
    for i in range(10):
        ax.add_patch(Rectangle((0.50 + 0.043 * i, -0.20), 0.030, 0.065, facecolor=GREEN, edgecolor="none"))
    ax.text(0.17, -0.25, "Observation\n" + r"$B=3$", ha="center", va="top", fontsize=17.5, linespacing=1.12, color=ORANGE)
    ax.text(0.71, -0.25, "Comparator\n" + r"Raw-$B=10$", ha="center", va="top", fontsize=17.5, linespacing=1.12, color=GREEN)
    ax.set(xlim=(-0.10, 1.10), ylim=(-0.48, 1.28), xlabel=r"$x/L$", ylabel=r"$y/L$")
    ax.set_aspect("equal")
    ax.set_xticks([0, 0.5, 1])
    ax.set_yticks([0, 0.5, 1])
    ax.set_title("(a) Square cavity and disjoint sampling", loc="left", pad=12, fontsize=22, fontweight="bold", color=NAVY)

    # Cylinder geometry and native coordinates.
    ax2.set_facecolor("#F4F8FB")
    ax2.add_patch(Wedge((0, 0), 0.93, 0, 180, width=0.44, facecolor="#E7F2F6", edgecolor="none", alpha=0.95))
    ax2.add_patch(Wedge((0, 0), 0.57, 0, 180, width=0.10, facecolor="#F3B6BE", edgecolor="none", alpha=0.85))
    ax2.add_patch(Wedge((0, 0), 0.50, 0, 180, facecolor="white", edgecolor=NAVY, linewidth=2.0))
    for yy in (0.18, 0.38):
        ax2.add_patch(FancyArrowPatch((-1.35, yy), (-0.62, yy), arrowstyle="-|>", mutation_scale=18, linewidth=2.4, color=ORANGE))
    ax2.text(-1.34, 0.60, "incident rarefied flow", fontsize=23, color=ORANGE)
    ax2.text(0.66, 0.80, "compression layer", fontsize=22, color=TEAL)
    ax2.text(0.05, 0.62, "near-wall sampling band", fontsize=22, color=RED)
    ax2.plot([0.04, 0.34], [0.55, 0.40], color=RED, linestyle="--", linewidth=1.5)
    th = np.deg2rad(55)
    ax2.plot([0, 0.78 * np.cos(th)], [0, 0.78 * np.sin(th)], color=PURPLE, linewidth=1.8)
    ax2.add_patch(Arc((0, 0), 0.58, 0.58, theta1=0, theta2=55, color=PURPLE, linewidth=1.8))
    ax2.text(0.28, 0.12, r"$\theta$", fontsize=26, color=PURPLE)
    ax2.text(0, -0.09, r"cylinder centre $(x_c,y_c)$", ha="center", fontsize=21)
    ax2.text(0.0, -0.36, r"$r/D$ and $\theta$ define the geometry-native representation", ha="center", fontsize=21, color=NAVY)
    ax2.set(xlim=(-1.48, 1.45), ylim=(-0.44, 1.18), xlabel=r"$(x-x_c)/D$", ylabel=r"$(y-y_c)/D$")
    ax2.set_aspect("equal")
    ax2.set_xticks([-1, -0.5, 0, 0.5, 1])
    ax2.set_yticks([0, 0.5, 1])
    ax2.set_title("(b) Cylinder-native coordinates", loc="left", pad=12, fontsize=22, fontweight="bold", color=NAVY)
    save_vector(fig, out, "geometries_and_sampling")


def trim_white(image: Image.Image, threshold: int = 248) -> Image.Image:
    rgb = image.convert("RGB")
    arr = np.asarray(rgb)
    mask = np.any(arr < threshold, axis=2)
    if not np.any(mask):
        return rgb
    yy, xx = np.where(mask)
    pad = max(18, int(0.006 * max(rgb.size)))
    left = max(0, int(xx.min()) - pad)
    top = max(0, int(yy.min()) - pad)
    right = min(rgb.width, int(xx.max()) + pad + 1)
    bottom = min(rgb.height, int(yy.max()) + pad + 1)
    return rgb.crop((left, top, right, bottom))


def wrap_dense_figure(source: Path, output: Path) -> None:
    image = trim_white(Image.open(source))
    # The PNG is saved without resampling; the PDF wrapper retains the native
    # pixels and simply defines a clean, tightly cropped media box.
    png_path = output / source.name
    image.save(png_path, optimize=True)
    write_raster_pdf(png_path, output / f"{source.stem}.pdf")


def write_raster_pdf(png_path: Path, pdf_path: Path, width_in: float = 13.6) -> None:
    """Place a validated high-resolution PNG in a tightly sized PDF page.

    ReportLab streams the raster without asking Matplotlib to emit millions of
    contour paths, avoiding partial PDF files for dense unstructured fields.
    """
    with Image.open(png_path) as image:
        image.verify()
    with Image.open(png_path) as image:
        width_px, height_px = image.size
    width_pt = 72.0 * width_in
    height_pt = width_pt * height_px / width_px
    document = canvas.Canvas(str(pdf_path), pagesize=(width_pt, height_pt), pageCompression=1)
    document.drawImage(ImageReader(str(png_path)), 0, 0, width=width_pt, height=height_pt, preserveAspectRatio=True, mask="auto")
    document.showPage()
    document.save()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True, help="directory containing the original high-resolution PNG figures")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    set_style()
    workflow_figure(args.output)
    geometry_figure(args.output)
    for stem in LEGACY:
        wrap_dense_figure(args.source / f"{stem}.png", args.output)


if __name__ == "__main__":
    main()
