#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="${UNITY_WATCHTOWER_CONFIG:-${HOME}/.config/unity-watchtower/config.json}"
if [[ ! -f "${CONFIG_PATH}" ]]; then
  printf 'Configuration does not exist: %s\n' "${CONFIG_PATH}" >&2
  exit 2
fi

read_config() {
  python3 -c 'import json,sys; data=json.load(open(sys.argv[1], encoding="utf-8")); cur=data
for key in sys.argv[2].split("."):
    cur=cur[key]
print(cur)' "${CONFIG_PATH}" "$1"
}

REPOSITORY="$(read_config github.repository)"
BRANCH="$(read_config github.branch)"
STATUS_REPO="$(read_config github.status_repo)"
TOKEN_FILE_RAW="$(read_config github.token_file)"
ASKPASS_RAW="$(read_config github.askpass)"
TOKEN_FILE="${TOKEN_FILE_RAW/#\~/${HOME}}"
ASKPASS="${ASKPASS_RAW/#\~/${HOME}}"
APP_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$(dirname -- "${TOKEN_FILE}")" "${STATUS_REPO}"
install -m 700 "${APP_ROOT}/scripts/git-askpass.sh" "${ASKPASS}"

token="${UNITY_MONITOR_GITHUB_TOKEN:-}"
if [[ -z "${token}" && -r "${TOKEN_FILE}" && "${1:-}" != "--replace-token" ]]; then
  IFS= read -r token < "${TOKEN_FILE}"
fi
if [[ -z "${token}" ]]; then
  if [[ ! -r /dev/tty ]]; then
    printf 'Run this script interactively once so it can securely prompt for the GitHub token.\n' >&2
    exit 2
  fi
  printf 'GitHub fine-grained token for %s (input hidden): ' "${REPOSITORY}" > /dev/tty
  IFS= read -r -s token < /dev/tty
  printf '\n' > /dev/tty
fi
if [[ -z "${token}" ]]; then
  printf 'No GitHub token was supplied.\n' >&2
  exit 2
fi

umask 077
printf '%s\n' "${token}" > "${TOKEN_FILE}"
chmod 600 "${TOKEN_FILE}"

curl_config="$(mktemp)"
chmod 600 "${curl_config}"
printf 'header = "Accept: application/vnd.github+json"\n' > "${curl_config}"
printf 'header = "Authorization: Bearer %s"\n' "${token}" >> "${curl_config}"
printf 'header = "X-GitHub-Api-Version: 2022-11-28"\n' >> "${curl_config}"

api() {
  curl --config "${curl_config}" -fsS "$@"
}

owner="${REPOSITORY%%/*}"
name="${REPOSITORY#*/}"
if [[ "${owner}" == "${name}" ]]; then
  printf 'github.repository must use owner/name form.\n' >&2
  exit 2
fi

probe_file="$(mktemp)"
trap 'rm -f "${probe_file}" "${curl_config}"' EXIT
http_code="$(curl --config "${curl_config}" -sS -o "${probe_file}" -w '%{http_code}' \
  "https://api.github.com/repos/${REPOSITORY}")"

if [[ "${http_code}" == "404" ]]; then
  authenticated_owner="$(api https://api.github.com/user | python3 -c 'import json,sys; print(json.load(sys.stdin)["login"])')"
  if [[ "${authenticated_owner,,}" != "${owner,,}" ]]; then
    printf 'Token belongs to %s, but repository owner is %s.\n' "${authenticated_owner}" "${owner}" >&2
    exit 2
  fi
  payload="$(python3 -c 'import json,sys; print(json.dumps({"name":sys.argv[1],"private":True,"description":"Sanitized read-only Unity HPC status generated by Unity Watchtower","auto_init":False}))' "${name}")"
  if ! api -X POST https://api.github.com/user/repos -d "${payload}" >/dev/null; then
    printf 'Could not create the private repository. Create %s as a private empty repository and rerun this script.\n' "${REPOSITORY}" >&2
    exit 2
  fi
  printf 'Created private GitHub repository %s.\n' "${REPOSITORY}"
elif [[ "${http_code}" != "200" ]]; then
  printf 'GitHub access check failed with HTTP %s. Verify token access to %s.\n' "${http_code}" "${REPOSITORY}" >&2
  exit 2
else
  visibility="$(python3 -c 'import json,sys; print("private" if json.load(open(sys.argv[1], encoding="utf-8")).get("private") else "public")' "${probe_file}")"
  if [[ "${visibility}" != "private" ]]; then
    printf 'Refusing to publish Unity status: %s is not private.\n' "${REPOSITORY}" >&2
    exit 2
  fi
  printf 'Using existing private GitHub repository %s.\n' "${REPOSITORY}"
fi

export GIT_TERMINAL_PROMPT=0
export GIT_ASKPASS="${ASKPASS}"
export UNITY_MONITOR_TOKEN_FILE="${TOKEN_FILE}"
export UNITY_MONITOR_GITHUB_USERNAME="${owner}"

git_auth() {
  git -c credential.helper= -c credential.username="${owner}" "$@"
}

if [[ ! -d "${STATUS_REPO}/.git" ]]; then
  git_auth -C "${STATUS_REPO}" init -b "${BRANCH}"
  git_auth -C "${STATUS_REPO}" remote add origin "https://github.com/${REPOSITORY}.git"
fi
git_auth -C "${STATUS_REPO}" config user.name "Unity Watchtower"
git_auth -C "${STATUS_REPO}" config user.email "unity-watchtower@users.noreply.github.com"
git_auth -C "${STATUS_REPO}" remote set-url origin "https://github.com/${REPOSITORY}.git"

remote_head="$(git_auth -C "${STATUS_REPO}" ls-remote --heads origin "${BRANCH}" | awk 'NR==1{print $1}')"
if [[ -n "${remote_head}" ]]; then
  git_auth -C "${STATUS_REPO}" fetch origin "${BRANCH}"
  if git_auth -C "${STATUS_REPO}" rev-parse --verify HEAD >/dev/null 2>&1; then
    git_auth -C "${STATUS_REPO}" merge --ff-only "origin/${BRANCH}"
  else
    git_auth -C "${STATUS_REPO}" checkout -B "${BRANCH}" "origin/${BRANCH}"
  fi
fi

printf 'GitHub authentication and private status checkout are ready.\n'
